AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  MyFunction:
    Type: AWS::Serverless::Function

    Metadata:
      DockerContext: prod
      Dockerfile: Dockerfile
      DockerBuildArgs:
        DEST: aws

    Properties:

      ...
